# Generated by Django 4.2.19 on 2025-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0002_car_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
        migrations.AddField(
            model_name="track",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tracks/"),
        ),
        migrations.AddField(
            model_name="track",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
