# Generated by Django 4.2.19 on 2025-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0003_track_description_track_image_track_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ride_option",
            field=models.CharField(
                choices=[
                    ("passenger", "Passenger Ride"),
                    ("with_instructor", "With Instructor"),
                    ("without_instructor", "Without Instructor"),
                ],
                default="passenger",
                max_length=20,
            ),
        ),
    ]
